### ISSUE TITLE
statik ip yerine No ip ?

### ISSUE THREAD

**Issue by HaresJK** [selimhallac/ziraatbankasi-web-eksktre-hesap-hareketleri#1]
Yerel Ağdaki Otomasyonumda Kullanmak İçin Başvuru Yapacağım. statik ip Yerine No-ip benzer Dynamic domain servislerinden Yararlanıp, Başvuru Dilekçesine Domain Adresi Yazarsam Başvurum Kabul Görürmü bilginiz varmı?

**Comment by selimhallac** [comment]
O konuda hiç bir fikrim yok :( Ama eğer öğrenirseniz buradanda paylaşırsanız süper olur, geç dönüşüm için kusura bakmayın :)

**Comment by HaresJK** [comment]
Olmuyor. Statik ip kulanan Bir serverda fonksiyon oluşturup bilgilerimi
post ederek verileri çektim. sabit ip şart yani. İyi çalışmalar :)

16 Kas 2021 Sal 14:01 tarihinde Selim Hallaç ***@***.***>
şunu yazdı:

**Comment by selimhallac** [comment]
Bende bu işler için ortak bir sunucu kullanıyorum, ona bir köprü oluşturdum tüm işlemleri o şekilde gerçekleştiriyorum. İyi çalışmalar
