### ISSUE TITLE
Kişisel Kullanım

### ISSUE THREAD

**Issue by tahayasinkoksal** [selimhallac/ziraatbankasi-web-eksktre-hesap-hareketleri#2]
Merhabalar, öncelikle paylaşım için teşekkürler. 

Test amaçlı reponun içindeki başvuru formunu indirdim. Biraz incelediğimde şirket ibaresi geçtiğini gördüm, acaba kişisel kullanım için başvuru yapılabilir mi, illa bir şirket için mi başvuru yapmak gerekli.

**Comment by selimhallac** [comment]
Selamlar, kişisel kullanım içinde başvuru yapabilirsiniz

**Comment by tahayasinkoksal** [comment]
Teşekkürler.
