### ISSUE TITLE
Bağlantı Hatası

### ISSUE THREAD

**Issue by tahayasinkoksal** [selimhallac/ziraatbankasi-web-eksktre-hesap-hareketleri#3]
Merhabalar, uzun uğraşlar sonucu bankamdan gerekli kullanıcı kodu ve şifreyi alabildim.
![image](https://user-images.githubusercontent.com/31388960/134377118-b8618963-5214-43ef-9027-65759971aa33.png)

Ufak bir sıkıntı var ne yaptıysam bilgilere erişim sağlayamadım, her şeyi doğru yaptığıma eminim.  Yazdığınız class ı kontrol ettim bana mail ile gönderilen url adresi ile sizinki farklı, değiştirip kullandım ama yine bir sonuç alamdım. 

Sayfa sürekli durmadan yükleniyor en sonunda sayfanın yüklenemediğine dair hata veriyor. Hosting adresimin ip si erişim adresi listesinde kayıtlı.
![image](https://user-images.githubusercontent.com/31388960/134378395-5c01c790-03d6-48cc-9869-1d935f6c0e50.png)

Nasıl çözebilirim acaba, yardımcı olabilirseniz çok sevinirim..

**Comment by tahayasinkoksal** [comment]
Çözüm: Bir kaç gün beklemek gerekli imiş.

**Comment by orhanerday** [comment]
@tahayasinkoksal  Merhaba bu bilgiyi nereden aldın?

**Comment by orhanerday** [comment]
@tahayasinkoksal Sorun çözüldü mü?

**Comment by tahayasinkoksal** [comment]
@orhanerday sorun yok, mail geldikten bir kaç gün sonra erişime açılıyor. Biraz beklemek gerekli.

**Comment by orhanerday** [comment]
@tahayasinkoksal çok teşekkürler.

**Comment by orhanerday** [comment]
@tahayasinkoksal  tam olarak kaç gün sonra erişime açıldı bir fikrin varmı?

**Comment by tahayasinkoksal** [comment]
@orhanerday inan hatırlamıyorum, sanki 3 veya 4 gün sonra açılmış olabilir. Sunucunun ip adresini doğru yazdığından emin ol derim.

**Comment by orhanerday** [comment]
@selimhallac merhaba bol bol rahatsız ediyorum kusura bakma 😂 iki hafta geçti sorun devam ediyor, yardım için bankadaki temsilcim ile görüştüm ben ilgilenmiyorum deyip kestirip attı. Acaba kimden yardım alabilirim bir fikrin var mı?
